"""Prove compatibility-view evidence and the finite read-only command boundary."""
from dataclasses import replace
from pathlib import Path
import unittest
from unittest.mock import call, patch

import offenders_iptables as ipt
from offenders_fail2ban import CommandFailure, CommandResult, Fail2BanParseError


PROPERTIES = {
    'actionban': '<iptables> -I f2b-<name> 1 -s <ip> -j <blocktype>',
    'iptables': 'iptables <lockingopt>', 'lockingopt': '-w',
    'iptables?family=inet6': 'ip6tables <lockingopt>',
    'name': 'guard', 'chain': 'INPUT',
    'blocktype': 'REJECT --reject-with icmp-port-unreachable',
    'blocktype?family=inet6': 'REJECT --reject-with icmp6-port-unreachable',
}
ACTIONSTART = (Path(__file__).parent / 'fixtures' / 'iptables-actionstart.txt').read_text().removesuffix('\n')


def save_text(source='192.0.2.1/32', target='REJECT --reject-with icmp-port-unreachable'):
    """Synthetic stock multiport snapshot, with a RETURN tail and unrelated table."""
    return ('# Generated by iptables-save\n*nat\n:INPUT ACCEPT [0:0]\n'
            ':f2b-guard - [0:0]\n-A INPUT -j f2b-guard\nCOMMIT\n'
            '*filter\n:INPUT ACCEPT [0:0]\n:f2b-guard - [0:0]\n'
            '-A INPUT -p tcp -m multiport --dports 22,2222 -j f2b-guard\n'
            f'-A f2b-guard -s {source} -j {target}\n'
            '-A f2b-guard -j RETURN\nCOMMIT\n# Completed\n')


class IptablesTests(unittest.TestCase):
    """Protect action selection, exact direct facts, and conservative failures."""

    def setUp(self):
        """Use foundation-normalized properties; never consult host action files."""
        self.action = ipt.classify_iptables_action(PROPERTIES)
        self.assertIsNotNone(self.action)

    def evidence(self, output, ip='192.0.2.1', action=None):
        """Verify one synthetic output through the public pure parser seam."""
        action = action or self.action
        snapshot = ipt.parse_iptables_save(output, action.save_binary)
        return ipt.verify_iptables_ban(action, ip, snapshot)

    def test_ipv4_ipv6_and_host_prefix_equivalence(self):
        """Unprefixed hosts and /32 or /128 prove the same exact host fact."""
        v6 = ipt.classify_iptables_action(PROPERTIES, family='inet6')
        for source in ['192.0.2.1', '192.0.2.1/32']:
            self.assertEqual(self.evidence(save_text(source)).outcome, 'confirmed')
        for source in ['2001:db8::1', '2001:0db8:0:0:0:0:0:1/128']:
            result = self.evidence(save_text(source, 'REJECT --reject-with icmp6-port-unreachable'),
                                   '2001:db8::1', v6)
            self.assertEqual((result.outcome, result.reason), ('confirmed', 'entry-observed'))
        drop = ipt.classify_iptables_action({**PROPERTIES, 'blocktype': 'DROP'})
        self.assertEqual(self.evidence(save_text(target='DROP'), action=drop).outcome, 'confirmed')
        # Save tools may normalize REJECT reply spelling; terminal targets agree.
        self.assertEqual(self.evidence(save_text(target='REJECT')).outcome, 'confirmed')

    def test_stock_known_chain_uses_start_parent_for_both_families(self):
        """Config-time known/chain is resolved in public actionstart, not a runtime tag."""
        properties = {**PROPERTIES, 'chain': '<known/chain>', 'actionstart': ACTIONSTART}
        action = ipt.classify_iptables_action(properties)
        self.assertEqual(action, self.action)
        self.assertEqual(self.evidence(save_text(), action=action).outcome, 'confirmed')
        v6 = ipt.classify_iptables_action(properties, family='inet6')
        self.assertEqual(v6, ipt.classify_iptables_action(PROPERTIES, family='inet6'))
        self.assertEqual(self.evidence(save_text('2001:db8::1', 'REJECT --reject-with icmp6-port-unreachable'),
                                       '2001:db8::1', v6).outcome, 'confirmed')

    def test_concrete_parent_ignores_start_and_start_never_confirms(self):
        """Concrete-chain callers need no start facts; start alone proves no live jump."""
        self.assertEqual(ipt.classify_iptables_action({**PROPERTIES, 'actionstart': 'arbitrary; command'}), self.action)
        properties = {**PROPERTIES, 'chain': '<known/chain>', 'actionstart': ACTIONSTART}
        action = ipt.classify_iptables_action(properties)
        without_jump = save_text().replace('-A INPUT -p tcp -m multiport --dports 22,2222 -j f2b-guard\n', '')
        self.assertEqual(self.evidence(without_jump, action=action).reason, 'parent-jump-absent')

    def test_start_parent_is_not_hardcoded_and_stock_scopes_agree(self):
        """Oneport/allports and a concrete custom parent retain the same direct model."""
        oneport = ACTIONSTART.replace('INPUT', 'PUBLIC_FILTER').replace('-m multiport --dports http,https', '--dport ssh')
        allports = ACTIONSTART.replace(' -m multiport --dports http,https', '').replace("'tcp'", "'tcp,udp'")
        self.assertEqual(ipt.classify_iptables_action({**PROPERTIES, 'chain': '<known/chain>',
                                                     'actionstart': oneport}).parent_chain, 'PUBLIC_FILTER')
        self.assertEqual(ipt.classify_iptables_action({**PROPERTIES, 'chain': '<known/chain>',
                                                     'actionstart': allports}).parent_chain, 'INPUT')

    def test_unqualified_start_cannot_authorize_a_parent(self):
        """Reject missing, ambiguous, unresolved, unsafe and custom command structures."""
        cases = {
            'absent': '',
            'malformed': ACTIONSTART.replace('done', ''),
            'non-shell-whitespace': ACTIONSTART.replace('-C INPUT', '-C\u2005INPUT'),
            'parent-mismatch': ACTIONSTART.replace('-I INPUT', '-I OUTPUT'),
            'multiple-parents': ACTIONSTART + '\n' + ACTIONSTART.replace('INPUT', 'OUTPUT'),
            'unresolved-parent': ACTIONSTART.replace('INPUT', '$chain'),
            'multiple-chains': ACTIONSTART.replace('INPUT', 'INPUT,OUTPUT'),
            'unsafe-parent': ACTIONSTART.replace('INPUT', 'INPUT;other'),
            'option-parent': ACTIONSTART.replace('INPUT', '-INPUT'),
            'wrong-target': ACTIONSTART.replace('f2b-guard', 'f2b-other'),
            'insert-target-mismatch': ACTIONSTART.replace('-j f2b-guard; }\ndone', '-j f2b-other; }\ndone'),
            'scope-mismatch': ACTIONSTART.replace('-I INPUT -p $proto', '-I INPUT -p tcp'),
            'custom-prefix': 'arbitrary; ' + ACTIONSTART,
            'custom-suffix': ACTIONSTART + '; arbitrary',
            'custom-loop': ACTIONSTART.replace("echo 'tcp'", 'custom'),
            'oversized': ACTIONSTART + ' ' * 65536,
        }
        for reason, raw in cases.items():
            with self.subTest(reason=reason), self.assertRaises(Fail2BanParseError):
                ipt.classify_iptables_action({**PROPERTIES, 'chain': '<known/chain>', 'actionstart': raw})
        with self.assertRaises(Fail2BanParseError):
            ipt.classify_iptables_action({**PROPERTIES, 'chain': '<known/chain>'})
        # Whitespace or an indirect reference does not activate the exact sentinel fallback.
        with self.assertRaises(Fail2BanParseError):
            ipt.classify_iptables_action({**PROPERTIES, 'chain': ' <known/chain>', 'actionstart': ACTIONSTART})

    def test_required_direct_facts_are_independent(self):
        """An unrelated table or chain cannot provide a missing filter fact."""
        output = save_text()
        cases = [
            (output.split('*filter')[0], 'filter-table-absent'),
            ('*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n', 'ban-chain-absent'),
            ('*filter\n:f2b-guard - [0:0]\n-A f2b-guard -s 192.0.2.1 -j REJECT\nCOMMIT\n', 'parent-chain-absent'),
            (output.replace('-A INPUT -p tcp -m multiport --dports 22,2222 -j f2b-guard\n', ''), 'parent-jump-absent'),
            (save_text('192.0.2.2'), 'ban-entry-absent'),
            (save_text('192.0.2.0/24'), 'ban-entry-absent'),
            (save_text(target='ACCEPT'), 'blocking-target-absent'),
            (save_text(target='DROP'), 'blocking-target-absent'),
        ]
        for text, reason in cases:
            with self.subTest(reason=reason):
                result = self.evidence(text)
                self.assertEqual((result.outcome, result.reason), ('missing', reason))

    def test_no_recursive_jump_or_restricted_host_confirmation(self):
        """Goto/custom jump paths and narrowed or negated rules prove no stock ban."""
        indirect = save_text().replace(':f2b-guard - [0:0]\n', ':f2b-guard - [0:0]\n:custom - [0:0]\n')
        indirect = indirect.replace('--dports 22,2222 -j f2b-guard', '--dports 22,2222 -j custom')
        indirect = indirect.replace('-A f2b-guard -j RETURN', '-A custom -j f2b-guard\n-A f2b-guard -j RETURN')
        self.assertEqual(self.evidence(indirect).reason, 'parent-jump-absent')
        self.assertEqual(self.evidence(save_text().replace('--dports 22,2222 -j', '--dports 22,2222 -g')).reason,
                         'parent-jump-absent')
        for extra in ['! -s 192.0.2.1', '-s 192.0.2.1 -p tcp --dport 80',
                      '-s 192.0.2.1 -s 192.0.2.2', '-s 192.0.2.1 -m mystery --opaque value']:
            with self.subTest(extra=extra):
                self.assertEqual(self.evidence(save_text().replace('-s 192.0.2.1/32', extra)).outcome,
                                 'unverifiable')
        self.assertEqual(self.evidence(save_text(target='custom')).reason, 'blocking-target-absent')

    def test_quoted_comments_are_inert_and_aliases_normalize(self):
        """Quoted option-like text cannot manufacture a source or jump fact."""
        comment = save_text().replace('-s 192.0.2.1/32', '-m comment --comment "-s 192.0.2.1"')
        self.assertEqual(self.evidence(comment).reason, 'ban-entry-absent')
        annotated = save_text().replace('-A f2b-guard -s', '-A f2b-guard -m comment --comment "-j" --source')
        self.assertEqual(self.evidence(annotated.replace('-j REJECT', '--jump REJECT')).outcome, 'confirmed')

    def test_malformed_or_oversized_evidence_is_unverifiable(self):
        """Never salvage incomplete, ambiguous or badly quoted filter evidence."""
        for output in [save_text().replace('-s 192.0.2.1/32', '-s "192.0.2.1'),
                       save_text().replace('COMMIT\n# Completed', '# Completed'),
                       save_text() + '*filter\nCOMMIT\n',
                       save_text().replace(':INPUT ACCEPT [0:0]\n', ':INPUT ACCEPT [0:0]\n:INPUT ACCEPT [0:0]\n'),
                       save_text().replace('-A f2b-guard -j RETURN', '-A missing -j RETURN'),
                       save_text().replace('-s 192.0.2.1/32', '-s invalid'),
                       save_text().replace('-s 192.0.2.1/32', '-s'),
                       'garbage', 'COMMIT\n', '*filter\nCOMMIT\n*nat\n',
                       'x' * (ipt.IPTABLES_TEXT_LIMIT + 1),
                       'é' * (ipt.IPTABLES_TEXT_LIMIT // 2 + 1)]:
            with self.subTest(output=output[:100]):
                self.assertEqual(self.evidence(output).outcome, 'unverifiable')
        self.assertEqual(self.evidence('').reason, 'filter-table-absent')

    def test_binary_mapping_and_effective_stock_shape(self):
        """Only six matching compatibility save views can be selected."""
        for family, prefix in [('inet4', 'iptables'), ('inet6', 'ip6tables')]:
            for suffix in ['', '-nft', '-legacy']:
                executable = prefix + suffix
                properties = {key: value for key, value in PROPERTIES.items() if '?family=' not in key}
                properties['iptables'] = executable + ' <lockingopt>'
                properties['blocktype'] = 'DROP'
                with self.subTest(executable=executable):
                    action = ipt.classify_iptables_action(properties, family=family)
                    self.assertEqual(action.save_binary, executable + '-save')
                    self.assertEqual(action.ip_version, 6 if family == 'inet6' else 4)
        effective = {**PROPERTIES, 'actionban': 'iptables -w -I f2b-guard 1 -s <ip> -j REJECT --reject-with icmp-port-unreachable'}
        self.assertEqual(ipt.classify_iptables_action(effective), self.action)
        self.assertIsNotNone(ipt.classify_iptables_action({**PROPERTIES, 'lockingopt': ''}))

    def test_unsupported_and_unresolved_actions_fail_closed(self):
        """Custom paths, wrappers, shell programs and unsupported targets never map."""
        self.assertIsNone(ipt.classify_iptables_action({'actionban': 'sendmail <ip>'}))
        for change in [{'iptables': '/usr/sbin/iptables -w'}, {'iptables': 'wrapper iptables'},
                       {'iptables': 'iptables-save'}, {'iptables': 'iptables -t filter'},
                       {'iptables': 'iptables --unknown'}, {'iptables': 'ip6tables -w'},
                       {'blocktype': 'LOG'}, {'blocktype': 'REJECT --reject-with unknown'},
                       {'blocktype': 'DROP --anything'}, {'actionban': '<iptables> -I f2b-<name> 1 -s <ip> -j <blocktype>; true'},
                       {'actionban': PROPERTIES['actionban'] + '\ntrue'},
                       {'actionban': PROPERTIES['actionban'].replace('<ip>', '192.0.2.1')},
                       {'actionban': PROPERTIES['actionban'].replace('<ip>', '<ip>/32')},
                       {'actionban': PROPERTIES['actionban'].replace(' 1 ', ' 2 ')},
                       {'actionban': '"unterminated <ip>'}]:
            with self.subTest(change=change):
                self.assertIsNone(ipt.classify_iptables_action({**PROPERTIES, **change}))
        for change in [{'name': 'unsafe;name'}, {'chain': '-option'}, {'name': '<name>'}]:
            with self.subTest(change=change), self.assertRaises(Fail2BanParseError):
                ipt.classify_iptables_action({**PROPERTIES, **change})
        with self.assertRaises(Fail2BanParseError):
            ipt.classify_iptables_action({key: value for key, value in PROPERTIES.items() if key != 'chain'})

    def test_matching_save_reads_only_once_without_arguments(self):
        """No action executable or restore/mutation form enters the sudo runner."""
        actions = [self.action, self.action]
        actions += [ipt.classify_iptables_action({**PROPERTIES, 'iptables': binary + ' -w'})
                    for binary in ['iptables-nft', 'iptables-legacy']]
        actions += [ipt.classify_iptables_action({**PROPERTIES, 'iptables?family=inet6': binary + ' -w'}, family='inet6')
                    for binary in ['ip6tables', 'ip6tables-nft', 'ip6tables-legacy']]
        with patch.object(ipt, 'run_host_command', return_value=CommandResult(0, save_text(), '')) as runner:
            snapshots = ipt.read_iptables_saves(actions)
        self.assertEqual(runner.call_args_list, [call([binary], timeout=8, sudo=True) for binary in snapshots])
        self.assertEqual(set(snapshots), {prefix + suffix + '-save' for prefix in ['iptables', 'ip6tables']
                                        for suffix in ['', '-nft', '-legacy']})
        self.assertNotIn('192.0.2.1/32', repr(snapshots))

    def test_failed_or_unsafe_read_never_means_missing(self):
        """Failures keep stable reason identities and discard raw command diagnostics."""
        for failure in CommandFailure:
            result = CommandResult(1, save_text(), 'private diagnostics', failure)
            with patch.object(ipt, 'run_host_command', return_value=result):
                snapshot = ipt.read_iptables_saves([self.action])[self.action.save_binary]
            evidence = ipt.verify_iptables_ban(self.action, '192.0.2.1', snapshot)
            self.assertEqual((evidence.outcome, evidence.reason), ('unverifiable', failure.value))
            self.assertNotIn('private', repr(snapshot))
        unsafe = replace(self.action, save_binary='iptables-restore')
        with patch.object(ipt, 'run_host_command') as runner:
            snapshot = ipt.read_iptables_saves([unsafe])[unsafe.save_binary]
        runner.assert_not_called()
        self.assertEqual(snapshot.reason, 'unsupported-save-binary')

    def test_snapshot_and_address_identity(self):
        """Wrong save view, invalid addresses and wrong families cannot confirm."""
        snapshot = ipt.parse_iptables_save(save_text(), self.action.save_binary)
        for ip, reason in [('invalid', 'invalid-ip'), ('2001:db8::1', 'ip-family-mismatch'),
                           ('fe80::1%eth0', 'ip-family-mismatch')]:
            result = ipt.verify_iptables_ban(self.action, ip, snapshot)
            self.assertEqual((result.outcome, result.reason), ('unverifiable', reason))
        other = replace(snapshot, save_binary='iptables-nft-save')
        self.assertEqual(ipt.verify_iptables_ban(self.action, '192.0.2.1', other).reason, 'snapshot-mismatch')


if __name__ == '__main__':
    unittest.main()
